name: flutter_profiler
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: "https://github.com/jonasermert/flutter_profiler"

environment:
  sdk: ^3.7.0

dependencies:


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
